app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}     

    oauth2:
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}

      facebook:
        client-id: ${FACEBOOK_CLIENT_ID}
        client-secret: ${FACEBOOK_CLIENT_SECRET}
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}/tornadodb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      pool-name: Prod-HikariPool
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
  mail:
    host: ${MAIL_SERVER}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
