spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/intranetdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:?31M@rs1975!}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: Dev-HikariPool
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
  mail:
    host: ${MAIL_SERVER:ssl0.ovh.net}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:admin@jdevhub.com}
    password: ${MAIL_PASSWORD:?31M@rs1975!}
