# --------------------------------------
# Déploiement de l'application backend
# --------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tornado-api
  labels:
    app: tornado-api
spec:
  replicas: 2  # Nombre de pods à exécuter
  selector:
    matchLabels:
      app: tornado-api
  template:
    metadata:
      labels:
        app: tornado-api
    spec:
      containers:
        - name: tornado-api
          image: nexus.jdevhub.com/tornado-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            # Variables non sensibles
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: tornado-api-config
                  key: SPRING_PROFILES_ACTIVE
                  
           # Variables sensibles via secret
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: tornado-api-secrets
                  key: DB_URL
                  
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: tornado-api-secrets
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tornado-api-secrets
                  key: DB_PASSWORD     
                                    
            - name: MAIL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: tornado-api-secrets
                  key: MAIL_SERVER
                  
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: tornado-api-secrets
                  key: MAIL_PORT
                  
            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: tornado-api-secrets
                  key: MAIL_USERNAME
                  
                  
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tornado-api-secrets
                  key: MAIL_PASSWORD
                                                      
            - name: KAFKA_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: tornado-api-secrets
                  key: KAFKA_SERVERS
                  
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tornado-api-secrets
                  key: JWT_SECRET_KEY    
                             
                             
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: tornado-api-secrets
                  key: GOOGLE_CLIENT_ID   
                         
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tornado-api-secrets
                  key: GOOGLE_CLIENT_SECRET
                        
                        
            - name: FACEBOOK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: tornado-api-secrets
                  key: FACEBOOK_CLIENT_IDD
                                  
            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tornado-api-secrets
                  key: FACEBOOK_CLIENT_SECRET             
---
# --------------------------------------
# Service NodePort pour exposer le backend
# --------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: tornado-api
  labels:
    app: tornado-api
spec:
  type: NodePort  # Expose le service sur un port de chaque nœud
  selector:
    app: tornado-api
  ports:
    - name: http
      port: 8080        # Port sur lequel le service est exposé dans le cluster
      targetPort: 8080  # Port cible dans les pods
      nodePort: 30090   # Port accessible depuis l’extérieur du cluster (NodeIP:30090)
